-- Order Block su candle_indicators
ALTER TABLE candle_indicators
    ADD COLUMN IF NOT EXISTS in_ob_bullish BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS in_ob_bearish BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ob_high NUMERIC(24,12),
    ADD COLUMN IF NOT EXISTS ob_low NUMERIC(24,12),
    ADD COLUMN IF NOT EXISTS ob_direction VARCHAR(16),
    ADD COLUMN IF NOT EXISTS ob_strength NUMERIC(8,4),
    ADD COLUMN IF NOT EXISTS ob_filled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS dist_to_ob_pct NUMERIC(12,8);
