"""add_executed_signals_table

Revision ID: 57ae0facc0b4
Revises: c01762d926ca
Create Date: 2026-04-08 16:20:35.078218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ae0facc0b4'
down_revision: Union[str, Sequence[str], None] = 'c01762d926ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executed_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('pattern_name', sa.String(length=64), nullable=False),
    sa.Column('pattern_strength', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('quantity_tp1', sa.Float(), nullable=True),
    sa.Column('quantity_tp2', sa.Float(), nullable=True),
    sa.Column('entry_order_id', sa.Integer(), nullable=True),
    sa.Column('tp_order_id', sa.Integer(), nullable=True),
    sa.Column('sl_order_id', sa.Integer(), nullable=True),
    sa.Column('tp2_order_id', sa.Integer(), nullable=True),
    sa.Column('sl2_order_id', sa.Integer(), nullable=True),
    sa.Column('tws_status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executed_signals_executed_at', 'executed_signals', ['executed_at'], unique=False)
    op.create_index('idx_executed_signals_symbol_tf', 'executed_signals', ['symbol', 'timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_executed_signals_symbol_tf', table_name='executed_signals')
    op.drop_index('idx_executed_signals_executed_at', table_name='executed_signals')
    op.drop_table('executed_signals')
    # ### end Alembic commands ###
