"""add_partial_fill_tracking_to_executed_signals

Revision ID: 5a0e4c6955cb
Revises: 9861318d33f4
Create Date: 2026-04-14 18:38:14.492897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0e4c6955cb'
down_revision: Union[str, Sequence[str], None] = '9861318d33f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executed_signals', sa.Column('partial_fill', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('executed_signals', sa.Column('filled_qty', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('executed_signals', sa.Column('ordered_qty', sa.Numeric(precision=24, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executed_signals', 'ordered_qty')
    op.drop_column('executed_signals', 'filled_qty')
    op.drop_column('executed_signals', 'partial_fill')
    # ### end Alembic commands ###
