"""baseline_initial_schema

Revision ID: c01762d926ca
Revises: 
Create Date: 2026-04-07 20:41:34.906537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01762d926ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_notification_sent', 'symbol',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('candles', 'exchange',
               existing_type=sa.VARCHAR(length=32),
               comment='Venue / connector exchange id (e.g. binance for ccxt crypto spot).',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'exchange',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Venue / connector exchange id (e.g. binance for ccxt crypto spot).',
               existing_nullable=False)
    op.alter_column('alert_notification_sent', 'symbol',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
