"""add_close_tracking_columns_to_executed_signals

Revision ID: 9861318d33f4
Revises: a3b4c5d6e7f8
Create Date: 2026-04-14 18:05:24.793994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9861318d33f4'
down_revision: Union[str, Sequence[str], None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executed_signals', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('executed_signals', sa.Column('close_fill_price', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('executed_signals', sa.Column('realized_r', sa.Float(), nullable=True))
    op.add_column('executed_signals', sa.Column('close_outcome', sa.String(length=16), nullable=True))
    op.add_column('executed_signals', sa.Column('close_cause', sa.String(length=32), nullable=True))
    op.alter_column('executed_signals', 'entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False)
    op.alter_column('executed_signals', 'stop_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False)
    op.alter_column('executed_signals', 'take_profit_1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=True)
    op.alter_column('executed_signals', 'take_profit_2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executed_signals', 'take_profit_2',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('executed_signals', 'take_profit_1',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('executed_signals', 'stop_price',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('executed_signals', 'entry_price',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('executed_signals', 'close_cause')
    op.drop_column('executed_signals', 'close_outcome')
    op.drop_column('executed_signals', 'realized_r')
    op.drop_column('executed_signals', 'close_fill_price')
    op.drop_column('executed_signals', 'closed_at')
    # ### end Alembic commands ###
